RUN install2.r --error --skipinstalled \ 
  furrr \ 
  future.batchtools \ 
  gert \ 
  here \ 
  knitr \ 
  lavaan \ 
  moments \ 
  pander \ 
  patchwork \ 
  renv \ 
  report \ 
  rticles \ 
  slider \ 
  targets \ 
  tidyverse \ 
  usethis
RUN installGithub.r \ 
  aaronpeikert/repro@368b897d \ 
  rstudio/webshot2@f62e743
