# Generated by repro: do not edit by hand
# Please edit Dockerfiles in .repro/
FROM rocker/verse:4.0.3
ARG BUILD_DATE=2021-01-07
WORKDIR /home/rstudio
RUN MRAN=https://mran.microsoft.com/snapshot/${BUILD_DATE} \
  && echo MRAN=$MRAN >> /etc/environment \
  && export MRAN=$MRAN \
  && echo "options(repos = c(CRAN='$MRAN'), download.file.method = 'libcurl')" >> /usr/local/lib/R/etc/Rprofile.site
RUN apt-get update && apt-get install -y chromium-browser
RUN install2.r --error --skipinstalled \ 
  furrr \ 
  future.batchtools \ 
  here \ 
  lavaan \ 
  patchwork \ 
  slider \ 
  svglite \ 
  tidyverse \ 
  usethis
RUN installGithub.r \ 
  aaronpeikert/repro@7bfaf98 \ 
  rstudio/webshot2@f62e743
